
package br.com.webservice.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExemploServiceImplementacaoService", targetNamespace = "http://webservice.com.br/", wsdlLocation = "http://localhost:8080/exemplo?wsdl")
public class ExemploServiceImplementacaoService
    extends Service
{

    private final static URL EXEMPLOSERVICEIMPLEMENTACAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXEMPLOSERVICEIMPLEMENTACAOSERVICE_EXCEPTION;
    private final static QName EXEMPLOSERVICEIMPLEMENTACAOSERVICE_QNAME = new QName("http://webservice.com.br/", "ExemploServiceImplementacaoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/exemplo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXEMPLOSERVICEIMPLEMENTACAOSERVICE_WSDL_LOCATION = url;
        EXEMPLOSERVICEIMPLEMENTACAOSERVICE_EXCEPTION = e;
    }

    public ExemploServiceImplementacaoService() {
        super(__getWsdlLocation(), EXEMPLOSERVICEIMPLEMENTACAOSERVICE_QNAME);
    }

    public ExemploServiceImplementacaoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXEMPLOSERVICEIMPLEMENTACAOSERVICE_QNAME, features);
    }

    public ExemploServiceImplementacaoService(URL wsdlLocation) {
        super(wsdlLocation, EXEMPLOSERVICEIMPLEMENTACAOSERVICE_QNAME);
    }

    public ExemploServiceImplementacaoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXEMPLOSERVICEIMPLEMENTACAOSERVICE_QNAME, features);
    }

    public ExemploServiceImplementacaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExemploServiceImplementacaoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExemploService
     */
    @WebEndpoint(name = "ExemploServiceImplementacaoPort")
    public ExemploService getExemploServiceImplementacaoPort() {
        return super.getPort(new QName("http://webservice.com.br/", "ExemploServiceImplementacaoPort"), ExemploService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExemploService
     */
    @WebEndpoint(name = "ExemploServiceImplementacaoPort")
    public ExemploService getExemploServiceImplementacaoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.com.br/", "ExemploServiceImplementacaoPort"), ExemploService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXEMPLOSERVICEIMPLEMENTACAOSERVICE_EXCEPTION!= null) {
            throw EXEMPLOSERVICEIMPLEMENTACAOSERVICE_EXCEPTION;
        }
        return EXEMPLOSERVICEIMPLEMENTACAOSERVICE_WSDL_LOCATION;
    }

}
